server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingservice
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: RatingService
  config:
    import: optional:configserver:http://localhost:8083